version: '3.0'
volumes:
  pgsql:
services:
  api_app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db_app
    volumes:
      - ./src:/app/src
  db_app:
    image: postgres
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgsql:/var/lib/postgresql/data